const thumb = (url) =>
  `https://api.microlink.io/?url=${encodeURIComponent(url)}&embed=image.url`;

export const accommodation = {
  label: 'Base camp',
  status: 'Locked in ✓',
  name: 'The Meadow -- Yarra Valley Large Entertainer with Spa & Sauna',
  dates: 'June 26 – June 28, 2026',
  address: '13 Symonds Street, Yarra Glen 3775',
  description: 'Base camp for the weekend. Address is confirmed and details are coming. Just get there.',
  linkLabel: 'Booking.com listing',
  link: 'https://www.booking.com/hotel/au/the-meadow-yarra-valley-large-entertainer-with-spa-sauna.en-gb.html',
  image:
    'https://cf.bstatic.com/xdata/images/hotel/max1024x768/782549036.jpg?k=0478c1a20b9fb8d48eb0011566224c9141316799b9b008e43557b7c0b4585f1e&o=',
  imageAlt: 'The Meadow in Yarra Glen'
};

export const votingSections = [
  {
    key: 'fridayNight',
    day: 'Friday',
    title: 'Friday night',
    subtitle: 'Make the most of the house. Games, music, sauna, beer pong, eat something decent. The goal is to actually use the place, not just sit in the kitchen.',
    icon: 'nightlife',
    options: [
      {
        id: 'fri-pizza',
        title: 'Pizza oven night',
        description: "Sam's bringing his portable pizza oven. He'll make the dough, do the whole thing, and turn out genuinely decent pizzas without making it a whole personality. Help is welcome if you want in. Participation is not mandatory and this is not a team-building exercise.",
        cost: 'Shared grocery cost',
        timeConstraint: null,
        link: null,
        thumbnail: 'https://tse1.explicit.bing.net/th/id/OIP.t74QJoWjW0wTkYj5tETpEQHaEy?rs=1&pid=ImgDetMain&o=7&rm=3',
      },
      {
        id: 'fri-bbq',
        title: 'BBQ and burgers',
        description: 'Classic. No notes.',
        cost: 'Shared grocery cost',
        timeConstraint: null,
        link: null,
        thumbnail: 'https://tse3.mm.bing.net/th/id/OIP.e9erSNNQrd1vykMyz-igRwHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
      },
      {
        id: 'fri-takeaway',
        title: 'Takeaway',
        description: 'Order something, eat it, go to sleep.',
        cost: 'Pay individually',
        timeConstraint: null,
        link: null,
        thumbnail: 'https://static.vecteezy.com/system/resources/previews/060/562/387/non_2x/delicious-asian-takeout-meal-noodles-salad-crispy-chicken-in-boxes-soft-light-blurred-background-free-photo.jpg',
      },
      {
        id: 'other',
        title: 'Something else',
        description: 'Have a better idea? Write it in.',
        cost: null,
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
    ],
  },
  {
    key: 'saturdayMorning',
    day: 'Saturday',
    title: 'Saturday morning',
    subtitle: 'The odds of everyone being fully functional are somewhere between low and zero. Pick something that still works with a mild headache and questionable hydration.',
    icon: 'wb_sunny',
    options: [
      {
        id: 'sat-am-clay-public',
        title: 'Clay shooting (public session)',
        description: "You get a gun, clay targets, and one chance to pretend you've done this before. Zero alcohol beforehand is non-negotiable, which is quite the commitment given the night before. Closed shoes, no camo, no singlets. It's also cursed early.",
        cost: '~$80.50 pp',
        timeConstraint: 'Arrive 8:45am sharp -- no exceptions',
        link: 'https://www.melbournegunclub.com/come-and-try/',
        thumbnail: thumb('https://www.melbournegunclub.com/come-and-try/'),
      },
      {
        id: 'sat-am-minigolf',
        title: 'Mini golf and driving range',
        description: 'Low stakes, suspiciously fun, medium competitive. Someone in the group will take this way too seriously. That person is never who you expect.',
        cost: '$14-$29 pp depending on activity',
        timeConstraint: null,
        link: 'https://www.maroondahgolfpark.com.au/',
        thumbnail: 'https://images.squarespace-cdn.com/content/v1/658e5e5805acd37df4c4cf0a/b309544e-05d2-4f79-9c17-7f6249ce895c/YARRARANGESTOURISM1.jpeg?format=1000w',
      },
      {
        id: 'sat-am-chill',
        title: 'Chill morning and sleep in',
        description: 'We are going to be hungover. This is a legitimate option.',
        cost: 'Free',
        timeConstraint: null,
        link: null,
        thumbnail: 'https://tse3.mm.bing.net/th/id/OIP.2LYjVcmAzMwNUCZfAMJlfAHaEk?rs=1&pid=ImgDetMain&o=7&rm=3',
      },
      {
        id: 'sat-am-walk',
        title: 'Short walk -- Badger Weir',
        description: 'Badger Weir Picnic Area near Healesville. Easy 2.5km loop through mountain ash forest. No gear required.',
        cost: 'Free',
        timeConstraint: null,
        link: 'https://www.parks.vic.gov.au/places-to-see/sites/badger-weir-picnic-area',
        thumbnail: thumb('https://www.parks.vic.gov.au/places-to-see/sites/badger-weir-picnic-area'),
      },
      {
        id: 'sat-am-donna-buang',
        title: 'Mt Donna Buang and Rainforest Gallery',
        description: 'Short drive from Yarra Glen. Rainforest boardwalk, lookout tower, misty trees. Requires no effort.',
        cost: 'Free',
        timeConstraint: null,
        link: 'https://www.parks.vic.gov.au/places-to-see/parks/yarra-ranges-national-park',
        thumbnail: thumb('https://www.parks.vic.gov.au/places-to-see/parks/yarra-ranges-national-park'),
      },
      {
        id: 'sat-am-tennis',
        title: 'Yarra Glen Tennis Club',
        description: "Bring racquets, balls, and court shoes. Classic. Respectable. Deeply unglamorous for a bucks weekend but we don't judge.",
        cost: '$20/hour',
        timeConstraint: 'BYO gear -- racquets and balls',
        link: 'https://play.tennis.com.au/yarraglentennisclub',
        thumbnail: 'https://play.tennis.com.au/Library/yarraglentennisclub?command=Proxy&type=Images&currentFolder=%2f&fileName=Court+Hire+Photo.jpg&thumbnail=Court+Hire+Photo__427x320.jpg&cache=31536000',
      },
      {
        id: 'other',
        title: 'Something else',
        description: 'Have a better idea? Write it in.',
        cost: null,
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
    ],
  },
  {
    key: 'saturdayLunch',
    day: 'Saturday',
    title: 'Saturday lunch / winery',
    subtitle: 'This is the Yarra Valley. There will be wine regardless.',
    icon: 'restaurant',
    options: [
      {
        id: 'sat-lunch-yering',
        title: 'Yering Station',
        description: 'Iconic Yarra Valley estate. Cellar door tastings and restaurant on site.',
        cost: null,
        timeConstraint: null,
        link: 'https://www.yering.com/visit-us/cellar-door/',
        thumbnail: 'https://www.yering.com/wp-content/uploads/960x800-50-50-Content-Tasting-Bar.jpg.webp',
      },
      {
        id: 'sat-lunch-rochford',
        title: 'Rochford Wines',
        description: 'Large cellar door with outdoor seating. Good food, live music on weekends.',
        cost: null,
        timeConstraint: null,
        link: 'https://rochfordwines.com.au/yarra-valley-cellar-door',
        thumbnail: 'https://rochfordwines.com.au/img/cellar-door-1.jpg',
      },
      {
        id: 'sat-lunch-chandon',
        title: 'Chandon',
        description: 'The sparkling wine place. Structured tasting experience. Worth it if you like bubbles.',
        cost: null,
        timeConstraint: null,
        link: 'https://www.chandon.com.au/Experiences',
        thumbnail: 'https://www.chandon.com.au/assets/images/contentblock/photos/750x500TastingBar.png',
      },
      {
        id: 'sat-lunch-oakridge',
        title: 'Oakridge Wines',
        description: 'More refined end of the spectrum. Good if the group wants a sit-down experience.',
        cost: null,
        timeConstraint: null,
        link: 'https://oakridgewines.com.au/cellar-door/',
        thumbnail: thumb('https://oakridgewines.com.au/cellar-door/'),
      },
      {
        id: 'sat-lunch-debortoli',
        title: 'De Bortoli -- Locale restaurant',
        description: 'Full restaurant experience on the estate. Better for a proper lunch than a tasting crawl.',
        cost: null,
        timeConstraint: null,
        link: 'https://www.debortoli.com.au/visit-us/restaurants/locale-restaurant-yarra-valley',
        thumbnail: thumb('https://www.debortoli.com.au/visit-us/restaurants/locale-restaurant-yarra-valley'),
      },
      {
        id: 'other',
        title: 'Something else',
        description: 'Have a better idea? Write it in.',
        cost: null,
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
    ],
  },
  {
    key: 'saturdayDrinks',
    day: 'Saturday',
    title: 'Saturday arvo',
    subtitle: 'Afternoon options -- not all of them are drinking, but some of them are. Distillery tour, brewery, more tastings, or just heading back to the house earlier. Pick what fits the day.',
    icon: 'liquor',
    options: [
      {
        id: 'sat-arvo-fourpillars',
        title: 'Four Pillars Gin',
        description: 'Healesville distillery. Guided tasting experience, about 55 mins. Hourly sessions from 12pm on weekends.',
        cost: '~$50 pp',
        timeConstraint: 'Hourly sessions -- needs to be booked in advance',
        link: 'https://fourpillarsgin.com/pages/visit-our-distillery',
        thumbnail: 'https://fourpillarsgin.com/cdn/shop/files/FPGSignage_hdavison_3275_10a1d187-784a-459c-a07c-b44023634e5f.webp?v=1703199456&width=750',
      },
      {
        id: 'sat-arvo-watts',
        title: 'Watts River Brewing',
        description: 'Local craft brewery in Healesville. Walk in, order beers, sit outside. No structure required.',
        cost: 'Pay as you go',
        timeConstraint: null,
        link: 'https://wattsriverbrewing.com.au/',
        thumbnail: thumb('https://wattsriverbrewing.com.au/'),
      },
      {
        id: 'sat-arvo-winery',
        title: 'More winery tastings',
        description: 'Continue from whichever winery we did at lunch. Or hit a second one.',
        cost: 'Depends on venue',
        timeConstraint: null,
        link: null,
        thumbnail: 'https://rochfordwines.com.au/img/winemaking-the-fruit.jpg',
      },
      {
        id: 'sat-arvo-donna-buang',
        title: 'Mt Donna Buang and Rainforest Gallery',
        description: 'If we skipped it in the morning, this still works in the afternoon.',
        cost: 'Free',
        timeConstraint: null,
        link: 'https://www.parks.vic.gov.au/places-to-see/parks/yarra-ranges-national-park',
        thumbnail: thumb('https://www.parks.vic.gov.au/places-to-see/parks/yarra-ranges-national-park'),
      },
      {
        id: 'sat-arvo-minigolf',
        title: 'Mini golf and driving range',
        description: 'Maroondah Golf Park. Works as an afternoon option too.',
        cost: '$14-$29 pp depending on activity',
        timeConstraint: null,
        link: 'https://www.maroondahgolfpark.com.au/',
        thumbnail: thumb('https://www.maroondahgolfpark.com.au/'),
      },
      {
        id: 'other',
        title: 'Something else',
        description: 'Have a better idea? Write it in.',
        cost: null,
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
    ],
  },
  {
    key: 'saturdayNight',
    day: 'Saturday',
    title: 'Saturday night',
    subtitle: "The back nine. Dinner at the house, keep the night going. We've got a good spot -- may as well use it properly.",
    icon: 'local_bar',
    options: [
      {
        id: 'sat-night-pizza',
        title: 'Pizza oven night',
        description: 'Only valid if we did BBQ on Friday. Same deal -- everyone helps, nobody supervises from a distance with a beer.',
        cost: 'Shared grocery cost',
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
      {
        id: 'sat-night-pub',
        title: 'Pub or restaurant dinner',
        description: 'Yarra Valley Grand or similar. Sit down, order from a menu, let someone else cook.',
        cost: 'Pay individually',
        timeConstraint: null,
        link: 'https://yarravalleygrand.com.au/',
        thumbnail: 'https://yarravalleygrand.com.au/wp-content/uploads/2024/11/Yarra-Valley-Grand-Hotel-HT-12th-March_GRIFFIN-SIMM_Finals_111-1-1290x570.jpg',
      },
      {
        id: 'sat-night-bbq',
        title: 'BBQ at the Airbnb',
        description: 'Simple, low effort, no logistics. Grill things, eat things.',
        cost: 'Shared grocery cost',
        timeConstraint: null,
        link: null,
        thumbnail: 'https://tse3.mm.bing.net/th/id/OIP.e9erSNNQrd1vykMyz-igRwHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
      },
      {
        id: 'sat-night-takeaway',
        title: 'Big takeaway order',
        description: 'Order a lot of food. Eat it on the couch.',
        cost: 'Pay individually or split',
        timeConstraint: null,
        link: null,
        thumbnail: 'https://static.vecteezy.com/system/resources/previews/060/562/387/non_2x/delicious-asian-takeout-meal-noodles-salad-crispy-chicken-in-boxes-soft-light-blurred-background-free-photo.jpg',
      },
      {
        id: 'other',
        title: 'Something else',
        description: 'Have a better idea? Write it in.',
        cost: null,
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
    ],
  },
  {
    key: 'sundayRecovery',
    day: 'Sunday',
    title: 'Sunday recovery',
    subtitle: 'Sunday is the vibe check. How bad is everyone actually feeling?',
    icon: 'coffee',
    options: [
      {
        id: 'sun-chocolaterie',
        title: 'Yarra Valley Chocolaterie',
        description: 'Free entry, optional tasting. Good hangover food decision.',
        cost: 'Free entry, ~$4 tasting',
        timeConstraint: null,
        link: 'https://www.yvci.com.au/',
        thumbnail: thumb('https://www.yvci.com.au/'),
      },
      {
        id: 'sun-donna-buang',
        title: 'Mt Donna Buang and Rainforest Gallery',
        description: 'Good final activity before driving home. Peaceful, low effort.',
        cost: 'Free',
        timeConstraint: null,
        link: 'https://www.parks.vic.gov.au/places-to-see/parks/yarra-ranges-national-park',
        thumbnail: thumb('https://www.parks.vic.gov.au/places-to-see/parks/yarra-ranges-national-park'),
      },
      {
        id: 'sun-minigolf',
        title: 'Mini golf and driving range',
        description: 'Maroondah Golf Park. Gentle, competitive, hungover-friendly.',
        cost: '$14-$29 pp depending on activity',
        timeConstraint: null,
        link: 'https://www.maroondahgolfpark.com.au/',
        thumbnail: 'https://images.squarespace-cdn.com/content/v1/658e5e5805acd37df4c4cf0a/b309544e-05d2-4f79-9c17-7f6249ce895c/YARRARANGESTOURISM1.jpeg?format=1000w',
      },
      {
        id: 'sun-tennis',
        title: 'Yarra Glen Tennis Club',
        description: 'BYO racquets and balls. Not provided. This is a very specific reminder.',
        cost: 'Free or minimal court fee',
        timeConstraint: 'BYO gear -- racquets and balls',
        link: 'https://play.tennis.com.au/yarraglentennisclub',
        thumbnail: 'https://play.tennis.com.au/Library/yarraglentennisclub?command=Proxy&type=Images&currentFolder=%2f&fileName=Court+Hire+Photo.jpg&thumbnail=Court+Hire+Photo__427x320.jpg&cache=31536000',
      },
      {
        id: 'sun-healesville',
        title: 'Healesville Sanctuary',
        description: 'Australian wildlife park. Wombats, platypus, eagles. Worth it if nobody has been.',
        cost: '~$54.50 pp',
        timeConstraint: 'Opens 9am, allow 2-3 hours',
        link: 'https://www.zoo.org.au/healesville/',
        thumbnail: thumb('https://www.zoo.org.au/healesville/'),
      },
      {
        id: 'sun-leave-early',
        title: 'Leave early',
        description: 'Respectable. No shame.',
        cost: 'Free',
        timeConstraint: null,
        link: null,
        thumbnail: 'https://i.imgflip.com/6l39ya.jpg',
      },
      {
        id: 'other',
        title: 'Something else',
        description: 'Have a better idea? Write it in.',
        cost: null,
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
    ],
  },
];

export const itineraryTimeline = [
  {
    day: 'Friday',
    entries: [
      { time: 'From 3pm', title: 'Arrive + settle in', note: 'Airbnb is open. First drink is imminent. Everything else figures itself out.', status: 'set' },
      { time: 'Evening', title: 'Friday dinner', note: 'TBC based on votes. Either way, someone will be late and that\'s on them.', status: 'pending' }
    ]
  },
  {
    day: 'Saturday',
    entries: [
      { time: 'Morning', title: 'Morning activity', note: 'TBC. Dress for it. Show up.', status: 'pending' },
      { time: 'Lunch', title: 'Winery lunch', note: 'TBC. Somewhere with good wine and enough food to absorb Saturday morning.', status: 'pending' },
      { time: 'Afternoon', title: 'Afternoon plans', note: 'TBC. See the vote page. Try to keep it together.', status: 'pending' },
      { time: 'Evening', title: 'Saturday dinner', note: 'TBC. The house is good. We\'re staying in it.', status: 'pending' }
    ]
  },
  {
    day: 'Sunday',
    entries: [
      { time: 'Morning', title: 'Recovery activity', note: 'Recovery activity TBC. Then everyone slowly disappears home.', status: 'pending' }
    ]
  }
];

export const essentialsChecklist = [
  'Warm layers. Yarra Valley in June will humble you.',
  'Phone charger and a portable one because you will forget',
  "Sleeping bag if you want your own warmth situation. The alternative is a group cuddle and that's your call.",
  'Electrolytes. Trust.',
  'Something to contribute to the house. Snacks, drinks, whatever.',
  'Low expectations for sleep, high expectations for everything else.',
  'Someone please remember to bring the groom.'
];
