const thumb = (url) =>
  `https://api.microlink.io/?url=${encodeURIComponent(url)}&embed=image.url`;

export const accommodation = {
  label: 'Base camp',
  status: 'Locked in ✓',
  name: 'Yarra Glen Airbnb Estate',
  dates: 'June 26 – June 28, 2026',
  address: 'TBC once shared',
  description: "Booked. Everyone ends up here. That's all you need to know for now.",
  linkLabel: 'See the place',
  link: 'https://www.airbnb.com.au/rooms/1561866387856977252?source_impression_id=p3_1776992856_P3BRBi61hmW3JbmH',
  image:
    'https://lh3.googleusercontent.com/aida-public/AB6AXuAWOjNCqmZTNLeJ1zl8g2cfwyETsA6rEuKHYT5V2QxA8iX7lmvfZqPNFKMN47SIq9akWxiYWs00tt7C_aWSZxIc3rzgDOP3d8eeJDozHxu5d7MRplHkwSp1Y2QYRmouj3g6BCWjsLjRPmOrqnQ1KCo9awWFQ1cX2IvhN5zzAxYIoT502d-AQH4jrcy9uoGiPjC1Tkh5XiQQ5nMO2osRohSDpZmw8rf8foV410LqiQCg2h2cg3PZh3Cq57G1gO5m9P3N1QPk41oDnoM',
  imageAlt: 'Luxury countryside Airbnb house in Yarra Valley at sunset'
};

export const votingSections = [
  {
    key: 'fridayNight',
    day: 'Friday',
    title: 'Friday night',
    subtitle: 'Arrive. Decompress. Eat something before anyone makes bad decisions.',
    icon: 'nightlife',
    options: [
      {
        id: 'fri-pizza',
        title: 'Pizza oven night',
        description: 'Sam brings the pizza oven. Everyone actually helps.',
        cost: 'Shared grocery cost',
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
      {
        id: 'fri-bbq',
        title: 'BBQ and burgers',
        description: 'Classic. No notes.',
        cost: 'Shared grocery cost',
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
      {
        id: 'fri-takeaway',
        title: 'Takeaway',
        description: 'Order something, eat it, go to sleep.',
        cost: 'Pay individually',
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
    ],
  },
  {
    key: 'saturdayMorning',
    day: 'Saturday',
    title: 'Saturday morning',
    subtitle: 'Probably the most physically demanding part of the weekend. Capitalise on being sober.',
    icon: 'wb_sunny',
    options: [
      {
        id: 'sat-am-clay-public',
        title: 'Clay shooting (public session)',
        description: 'Melbourne Gun Club in Yering. Walk-up session. Zero alcohol beforehand, closed shoes, no camo.',
        cost: '~$80.50 pp',
        timeConstraint: 'Arrive 8:45am sharp -- no exceptions',
        link: 'https://www.melbournegunclub.com/come-and-try/',
        thumbnail: thumb('https://www.melbournegunclub.com/come-and-try/'),
      },
      {
        id: 'sat-am-minigolf',
        title: 'Mini golf and driving range',
        description: 'Maroondah Golf Park. Open from 9am. Mix and match -- mini golf, range bays, or both.',
        cost: '$14-$29 pp depending on activity',
        timeConstraint: null,
        link: 'https://www.maroondahgolfpark.com.au/',
        thumbnail: thumb('https://www.maroondahgolfpark.com.au/'),
      },
      {
        id: 'sat-am-chill',
        title: 'Chill morning and sleep in',
        description: 'We are going to be hungover. This is a legitimate option.',
        cost: 'Free',
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
      {
        id: 'sat-am-walk',
        title: 'Short walk -- Badger Weir',
        description: 'Badger Weir Picnic Area near Healesville. Easy 2.5km loop through mountain ash forest. No gear required.',
        cost: 'Free',
        timeConstraint: null,
        link: 'https://www.parks.vic.gov.au/places-to-see/sites/badger-weir-picnic-area',
        thumbnail: thumb('https://www.parks.vic.gov.au/places-to-see/sites/badger-weir-picnic-area'),
      },
      {
        id: 'sat-am-donna-buang',
        title: 'Mt Donna Buang and Rainforest Gallery',
        description: 'Short drive from Yarra Glen. Rainforest boardwalk, lookout tower, misty trees. Requires no effort.',
        cost: 'Free',
        timeConstraint: null,
        link: 'https://www.parks.vic.gov.au/places-to-see/parks/yarra-ranges-national-park',
        thumbnail: thumb('https://www.parks.vic.gov.au/places-to-see/parks/yarra-ranges-national-park'),
      },
      {
        id: 'sat-am-tennis',
        title: 'Tennis at the Airbnb / local court',
        description: 'There are courts nearby. You need to bring your own racquets and balls -- this does not appear by magic.',
        cost: 'Free or minimal court fee',
        timeConstraint: 'BYO gear -- racquets and balls',
        link: null,
        thumbnail: null,
      },
    ],
  },
  {
    key: 'saturdayLunch',
    day: 'Saturday',
    title: 'Saturday lunch / winery',
    subtitle: 'This is the Yarra Valley. There will be wine regardless.',
    icon: 'restaurant',
    options: [
      {
        id: 'sat-lunch-yering',
        title: 'Yering Station',
        description: 'Iconic Yarra Valley estate. Cellar door tastings and restaurant on site.',
        cost: '~$15-$35 pp tastings',
        timeConstraint: null,
        link: 'https://www.yering.com/visit-us/cellar-door/',
        thumbnail: thumb('https://www.yering.com/visit-us/cellar-door/'),
      },
      {
        id: 'sat-lunch-rochford',
        title: 'Rochford Wines',
        description: 'Large cellar door with outdoor seating. Good food, live music on weekends.',
        cost: '~$15-$25 pp tastings',
        timeConstraint: null,
        link: 'https://rochfordwines.com.au/yarra-valley-cellar-door',
        thumbnail: thumb('https://rochfordwines.com.au/yarra-valley-cellar-door'),
      },
      {
        id: 'sat-lunch-chandon',
        title: 'Chandon',
        description: 'The sparkling wine place. Structured tasting experience. Worth it if you like bubbles.',
        cost: '~$22 pp tasting',
        timeConstraint: 'Bookings recommended',
        link: 'https://www.chandon.com.au/Experiences',
        thumbnail: thumb('https://www.chandon.com.au/Experiences'),
      },
      {
        id: 'sat-lunch-oakridge',
        title: 'Oakridge Wines',
        description: 'More refined end of the spectrum. Good if the group wants a sit-down experience.',
        cost: 'Enquire for group pricing',
        timeConstraint: null,
        link: 'https://oakridgewines.com.au/cellar-door/',
        thumbnail: thumb('https://oakridgewines.com.au/cellar-door/'),
      },
      {
        id: 'sat-lunch-debortoli',
        title: 'De Bortoli -- Locale restaurant',
        description: 'Full restaurant experience on the estate. Better for a proper lunch than a tasting crawl.',
        cost: 'Restaurant pricing',
        timeConstraint: 'Booking required for groups',
        link: 'https://www.debortoli.com.au/visit-us/restaurants/locale-restaurant-yarra-valley',
        thumbnail: thumb('https://www.debortoli.com.au/visit-us/restaurants/locale-restaurant-yarra-valley'),
      },
    ],
  },
  {
    key: 'saturdayDrinks',
    day: 'Saturday',
    title: 'Saturday afternoon drinks',
    subtitle: 'Afternoon drinks are happening. The only vote is where.',
    icon: 'liquor',
    options: [
      {
        id: 'sat-arvo-fourpillars',
        title: 'Four Pillars Gin',
        description: 'Healesville distillery. Guided tasting experience, about 55 mins. Hourly sessions from 12pm on weekends.',
        cost: '~$50 pp',
        timeConstraint: 'Hourly sessions -- needs to be booked in advance',
        link: 'https://fourpillarsgin.com/pages/visit-our-distillery',
        thumbnail: thumb('https://fourpillarsgin.com/pages/visit-our-distillery'),
      },
      {
        id: 'sat-arvo-watts',
        title: 'Watts River Brewing',
        description: 'Local craft brewery in Healesville. Walk in, order beers, sit outside. No structure required.',
        cost: 'Pay as you go',
        timeConstraint: null,
        link: 'https://wattsriverbrewing.com.au/',
        thumbnail: thumb('https://wattsriverbrewing.com.au/'),
      },
      {
        id: 'sat-arvo-winery',
        title: 'More winery tastings',
        description: 'Continue from whichever winery we did at lunch. Or hit a second one.',
        cost: 'Depends on venue',
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
      {
        id: 'sat-arvo-donna-buang',
        title: 'Mt Donna Buang and Rainforest Gallery',
        description: 'If we skipped it in the morning, this still works in the afternoon.',
        cost: 'Free',
        timeConstraint: null,
        link: 'https://www.parks.vic.gov.au/places-to-see/parks/yarra-ranges-national-park',
        thumbnail: thumb('https://www.parks.vic.gov.au/places-to-see/parks/yarra-ranges-national-park'),
      },
      {
        id: 'sat-arvo-minigolf',
        title: 'Mini golf and driving range',
        description: 'Maroondah Golf Park. Works as an afternoon option too.',
        cost: '$14-$29 pp depending on activity',
        timeConstraint: null,
        link: 'https://www.maroondahgolfpark.com.au/',
        thumbnail: thumb('https://www.maroondahgolfpark.com.au/'),
      },
    ],
  },
  {
    key: 'saturdayNight',
    day: 'Saturday',
    title: 'Saturday night',
    subtitle: 'The back nine. Dinner. Chaos. Some regrets.',
    icon: 'local_bar',
    options: [
      {
        id: 'sat-night-pizza',
        title: 'Pizza oven night',
        description: 'Only valid if we did BBQ on Friday. Same deal -- everyone helps, nobody supervises from a distance with a beer.',
        cost: 'Shared grocery cost',
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
      {
        id: 'sat-night-pub',
        title: 'Pub or restaurant dinner',
        description: 'Yarra Valley Grand or similar. Sit down, order from a menu, let someone else cook.',
        cost: 'Pay individually',
        timeConstraint: null,
        link: 'https://yarravalleygrand.com.au/',
        thumbnail: thumb('https://yarravalleygrand.com.au/'),
      },
      {
        id: 'sat-night-bbq',
        title: 'BBQ at the Airbnb',
        description: 'Simple, low effort, no logistics. Grill things, eat things.',
        cost: 'Shared grocery cost',
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
      {
        id: 'sat-night-takeaway',
        title: 'Big takeaway order',
        description: 'Order a lot of food. Eat it on the couch.',
        cost: 'Pay individually or split',
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
    ],
  },
  {
    key: 'sundayRecovery',
    day: 'Sunday',
    title: 'Sunday recovery',
    subtitle: 'Sunday is the vibe check. How bad is everyone actually feeling?',
    icon: 'coffee',
    options: [
      {
        id: 'sun-chocolaterie',
        title: 'Yarra Valley Chocolaterie',
        description: 'Free entry, optional tasting. Good hangover food decision.',
        cost: 'Free entry, ~$4 tasting',
        timeConstraint: null,
        link: 'https://www.yvci.com.au/',
        thumbnail: thumb('https://www.yvci.com.au/'),
      },
      {
        id: 'sun-donna-buang',
        title: 'Mt Donna Buang and Rainforest Gallery',
        description: 'Good final activity before driving home. Peaceful, low effort.',
        cost: 'Free',
        timeConstraint: null,
        link: 'https://www.parks.vic.gov.au/places-to-see/parks/yarra-ranges-national-park',
        thumbnail: thumb('https://www.parks.vic.gov.au/places-to-see/parks/yarra-ranges-national-park'),
      },
      {
        id: 'sun-minigolf',
        title: 'Mini golf and driving range',
        description: 'Maroondah Golf Park. Gentle, competitive, hungover-friendly.',
        cost: '$14-$29 pp depending on activity',
        timeConstraint: null,
        link: 'https://www.maroondahgolfpark.com.au/',
        thumbnail: thumb('https://www.maroondahgolfpark.com.au/'),
      },
      {
        id: 'sun-tennis',
        title: 'Tennis at the Airbnb / local court',
        description: 'BYO racquets and balls. Not provided. This is a very specific reminder.',
        cost: 'Free or minimal court fee',
        timeConstraint: 'BYO gear -- racquets and balls',
        link: null,
        thumbnail: null,
      },
      {
        id: 'sun-healesville',
        title: 'Healesville Sanctuary',
        description: 'Australian wildlife park. Wombats, platypus, eagles. Worth it if nobody has been.',
        cost: '~$54.50 pp',
        timeConstraint: 'Opens 9am, allow 2-3 hours',
        link: 'https://www.zoo.org.au/healesville/',
        thumbnail: thumb('https://www.zoo.org.au/healesville/'),
      },
      {
        id: 'sun-leave-early',
        title: 'Leave early',
        description: 'Respectable. No shame.',
        cost: 'Free',
        timeConstraint: null,
        link: null,
        thumbnail: null,
      },
    ],
  },
];

export const itineraryTimeline = [
  {
    day: 'Friday',
    entries: [
      { time: 'From 3pm', title: 'Arrive + settle in', note: 'Airbnb opens. Find your room. First drink happens. Timeline from here is flexible.', status: 'set' },
      { time: 'Evening', title: 'Friday dinner', note: 'TBC based on votes. Either way, someone will be late.', status: 'pending' }
    ]
  },
  {
    day: 'Saturday',
    entries: [
      { time: 'Morning', title: 'Morning activity', note: 'Activity TBC. Dress accordingly. Show up on time.', status: 'pending' },
      { time: 'Lunch', title: 'Winery / lunch', note: 'Winery lunch TBC. Group booking needed once confirmed.', status: 'pending' },
      { time: 'Afternoon', title: 'Afternoon drinks', note: 'Afternoon drinks TBC. Bring your liver.', status: 'pending' },
      { time: 'Evening', title: 'Saturday dinner', note: 'Dinner TBC. Hopefully someone else is cooking.', status: 'pending' }
    ]
  },
  {
    day: 'Sunday',
    entries: [
      { time: 'Morning', title: 'Recovery activity', note: 'Recovery activity TBC. Then everyone slowly disappears home.', status: 'pending' }
    ]
  }
];

export const essentialsChecklist = [
  'Warm layers -- Yarra Valley in June is not a vibe without them',
  'Phone charger and a portable one because you will forget',
  'Electrolytes. Trust.',
  'Something to contribute to the house -- snacks, drinks, whatever',
  'Low expectations for sleep, high expectations for everything else'
];
